GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};

GRANT USAGE ON SCHEMA public TO ${POSTGRES_USER};
GRANT CREATE ON SCHEMA public TO ${POSTGRES_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_USER};

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ${POSTGRES_USER};