services:
  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SONARQUBE_PORT=${SONARQUBE_PORT}
        - SONARQUBE_DB_USER=${SONARQUBE_DB_USER}
        - SONARQUBE_DB_PASSWORD=${SONARQUBE_DB_PASSWORD}
        - SONARQUBE_DB_HOST=${SONARQUBE_DB_HOST}
        - SONARQUBE_DB_PORT=${SONARQUBE_DB_PORT}
        - SONARQUBE_DB_NAME=${SONARQUBE_DB_NAME}
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    env_file:
      - .env
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "${SONARQUBE_PORT}:${SONARQUBE_PORT}"

  sonarqube_db:
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - SONARQUBE_DB_USER=${SONARQUBE_DB_USER}
        - SONARQUBE_DB_PASSWORD=${SONARQUBE_DB_PASSWORD}
        - SONARQUBE_DB_NAME=${SONARQUBE_DB_NAME}
    container_name: sonarqube_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}

volumes:
  db_data:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
