services:
  cosign-sign:
    depends_on:
      - certificate-generator
      - backend-api
      - backend-event-streamer
      - alert-manager
      - reverse-proxy
    build:
      context: ./cosign-sign
      dockerfile: Dockerfile
      args:
        - COSIGN_VERSION=${COSIGN_VERSION}
    container_name: cosign_sign
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/cosign:/certs/cosign:ro
    environment:
      - COSIGN_PRIVATE_KEY_PATH=/certs/cosign/cosign.key
      - COSIGN_PUBLIC_KEY_PATH=/certs/cosign/cosign.pub
    networks:
      - backend
    command: ["/bin/sh", "/cosign_setup_and_sign.sh"]

  trivy-scan:
    depends_on:
      - backend-api
      - backend-event-streamer
      - message-broker
    build:
      context: ./trivy-scan
      dockerfile: Dockerfile
      args:
        - TRIVYSCAN_VERSION=${TRIVYSCAN_VERSION}
    container_name: trivy_scan
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./trivy-scan/reports:/reports
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - backend
