services:
  reverse-proxy:
    depends_on:
      - certificate-generator
      - backend-api
      - grafana
      - prometheus
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - BACKEND_API_PORT=${BACKEND_API_PORT}
        - PROMETHEUS_PORT=${PROMETHEUS_PORT}
        - GRAFANA_PORT=${GRAFANA_PORT}
        - CADVISOR_PORT=${CADVISOR_PORT}
    container_name: nginx_proxy
    volumes:
      - ./certs/ssl:/certs/ssl:ro
      - logs:/logs
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
      - "${NGINX_SSL_PORT}:${NGINX_SSL_PORT}"
    networks:
      - backend
    command: ["/bin/sh", "/setup-proxy-certificates.sh"]

volumes:
  logs:
    driver: local

networks:
  backend:
    driver: bridge
