networks:
  backend:
    driver: bridge

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  alertmanager_config:
    driver: local
  alertmanager_data:
    driver: local
  logs:
    driver: local