name:                backend
version:             0.1.0.0
github:              "githubuser/backend"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/backend#readme>

dependencies:
- base >= 4.7 && < 5
- servant >= 0.18
- servant-server >= 0.18
- postgresql-simple >= 0.6.4
- wai >= 3.2
- warp >= 3.3
- aeson >= 1.5.6.0
- persistent >= 2.13.0.0
- persistent-postgresql >= 2.13.0.0
- uuid >= 1.3.13
- time >= 1.9.3
- text
- hedis
- bytestring >= 0.11.5.3
- fast-logger
- network >= 3.1.4.0
- regex-tdfa >= 1.3.1.0
- jwt
- containers
- cryptonite
- base64-bytestring
- memory
- http-types >= 0.12.4
- wai-extra >= 3.1.15
- scientific
- mtl >= 2.3.1
- unordered-containers >= 0.2.20

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend

tests:
  backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
