global:
  scrape_interval: 15s
  evaluation_interval: 15s  

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alert-manager:9093'] 
        
rule_files:
  - alert.rules.yml 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']