CREATE DATABASE ${SONARQUBE_DB_NAME};

CREATE USER ${SONARQUBE_DB_USER} WITH ENCRYPTED PASSWORD '${SONARQUBE_DB_PASSWORD}';

\c ${SONARQUBE_DB_NAME}

GRANT CONNECT ON DATABASE ${SONARQUBE_DB_NAME} TO ${SONARQUBE_DB_USER};

GRANT USAGE ON SCHEMA public TO ${SONARQUBE_DB_USER};
GRANT CREATE ON SCHEMA public TO ${SONARQUBE_DB_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${SONARQUBE_DB_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${SONARQUBE_DB_USER};

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${SONARQUBE_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ${SONARQUBE_DB_USER};
