server:
  http_listen_port: ${PROMTAIL_PORT} 

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://${LOKI_HOST}:${LOKI_PORT}/loki/api/v1/push

scrape_configs:
  - job_name: "nginx-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "nginx"
          __path__: ${NGINX_LOG_PATH}